function $(selector, root=document){return root.querySelector(selector)}
function $$(selector, root=document){return [...root.querySelectorAll(selector)]}
function showNotice(message,type="info",target="#notice"){
  const el=typeof target==="string"?$(target):target;if(!el)return;
  el.className=`notice ${type}`;el.textContent=String(message||"");el.hidden=false;
  clearTimeout(el._timer);el._timer=setTimeout(()=>el.hidden=true,7000);
}
function money(value){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(value)||0)}
function formatDate(value){if(!value)return "—";const d=new Date(Number(value));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}

// Natural read-aloud: prefer installed "Natural"/Online/Enhanced voices and keep a normal speaking rate.
// The browser/device supplies the actual voice engine; no artificial robotic voice is generated by MathCloud.
let mcSpeech={utterance:null,voices:[],timer:null};
function loadMCVoices(){try{mcSpeech.voices=window.speechSynthesis?.getVoices?.()||[]}catch(e){mcSpeech.voices=[]}}
if("speechSynthesis" in window){loadMCVoices();window.speechSynthesis.onvoiceschanged=()=>{loadMCVoices()}}
function pickMCVoice(){
  const voices=mcSpeech.voices||[];
  const english=voices.filter(v=>/^en(-|$)/i.test(String(v.lang||"")));
  const score=v=>{
    const n=String(v.name||"").toLowerCase(),l=String(v.lang||"").toLowerCase();
    let x=0;
    if(/natural|online|enhanced|neural|premium/.test(n)) x+=100;
    if(/microsoft|google|samantha|alex|daniel|karen|moira|serena|aria|guy|jenny|ryan|sonia/.test(n)) x+=35;
    if(/^en-ng$/.test(l)) x+=30;
    if(/^en-gb$/.test(l)) x+=20;
    if(/^en-us$/.test(l)) x+=15;
    if(/^en-/.test(l)) x+=5;
    return x;
  };
  return english.sort((a,b)=>score(b)-score(a))[0]||voices[0]||null;
}
function stopReadAloud(){try{window.speechSynthesis?.cancel()}catch(e){};mcSpeech.utterance=null}
function readAloudText(text,button=null){
  if(!text||!("speechSynthesis" in window)){showNotice("Read aloud is not available on this device. Try a current Chrome, Edge or Safari browser.","warning");return}
  const clean=String(text).replace(/\s+/g," ").trim();if(!clean)return;
  try{
    if(window.speechSynthesis.speaking){stopReadAloud();if(button)button.textContent="Read aloud";return}
    const u=new SpeechSynthesisUtterance(clean),voice=pickMCVoice();
    if(voice)u.voice=voice;
    u.lang=voice?.lang||"en-NG";
    u.rate=1.0;u.pitch=1.0;u.volume=1;
    u.onend=()=>{if(button)button.textContent="Read aloud";mcSpeech.utterance=null};
    u.onerror=()=>{if(button)button.textContent="Read aloud";mcSpeech.utterance=null};
    mcSpeech.utterance=u;
    if(button)button.textContent="Stop reading";
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
  }catch(e){console.warn("Read aloud failed",e);showNotice("Read aloud could not start on this device.","warning")}
}
function addReadAloudButton(target,sourceOrGetter=null,label="Read aloud"){
  if(!target)return null;
  let host=target.closest?.(".read-aloud-host")||target.parentElement;if(!host)host=target;
  let existing=host.querySelector?.(".read-aloud-btn");if(existing)return existing;
  const b=document.createElement("button");b.type="button";b.className="read-aloud-btn";b.textContent=label;
  b.title="Read this content aloud using the best natural English voice available on your device";
  b.setAttribute("aria-label",label);
  b.onclick=()=>{const raw=typeof sourceOrGetter==="function"?sourceOrGetter():sourceOrGetter??target.innerText??target.textContent;readAloudText(raw,b)};
  host.classList.add("read-aloud-host");host.insertBefore(b,target.nextSibling);return b;
}
function addReadAloudToSelector(selector,sourceOrGetter=null){return $$(selector).map(el=>addReadAloudButton(el,typeof sourceOrGetter==="function"?()=>sourceOrGetter(el):sourceOrGetter))}

function renderStudentWelcome(user,data,pageTitle=document.title){
  if(document.querySelector(".mc-page-welcome"))return;
  const first=String(data?.firstName||data?.displayName||user?.displayName||"Student").trim().split(/\s+/)[0]||"Student";
  const course=String(data?.course||"JAMB preparation").trim();
  const subjects=getStudentSubjects(data);
  const wrap=document.createElement("section");
  wrap.className="mc-page-welcome";
  wrap.innerHTML=`<div class="mc-welcome-icon">☁</div><div class="mc-welcome-copy"><span class="mc-eyebrow">MathCloud JAMB · ${escapeHtml(pageTitle.replace(/\s*[—|].*$/,"").trim()||"Learning centre")}</span><h2>Welcome back, ${escapeHtml(first)}.</h2><p>${escapeHtml(pageTitle.replace(/^.*?—\s*/,"").replace(/\s*\|.*$/,"").trim()||"Your learning space is ready.")} · ${escapeHtml(course)}${subjects.length?` · ${subjects.length} registered subject${subjects.length===1?"":"s"}`:""}.</p></div><div class="mc-welcome-badge">Your progress is saved automatically</div>`;
  const anchor=document.querySelector(".topbar")||document.querySelector("nav");
  if(anchor)anchor.insertAdjacentElement("afterend",wrap);
}
function mcCacheKey(path){return `mc-cache:${path}`}
const mcMemoryCache=new Map(),mcPendingReads=new Map();
async function mcRead(path,{ttl=45000,force=false}={}){
  const key=String(path||"");if(!key)return null;
  const now=Date.now(),hit=mcMemoryCache.get(key);
  if(!force&&hit&&now-hit.time<ttl)return hit.value;
  if(!force&&mcPendingReads.has(key))return mcPendingReads.get(key);
  const promise=db.ref(key).once("value").then(snap=>{const value=snap.val();mcMemoryCache.set(key,{time:Date.now(),value});return value}).finally(()=>mcPendingReads.delete(key));
  mcPendingReads.set(key,promise);return promise;
}
function mcForgetCache(prefix=""){for(const key of [...mcMemoryCache.keys()])if(!prefix||key===prefix||key.startsWith(prefix))mcMemoryCache.delete(key)}
async function mcQueryChild(path,child,value,{ttl=45000}={}){
  const key=`query:${path}|${child}|${String(value)}`,now=Date.now(),hit=mcMemoryCache.get(key);
  if(hit&&now-hit.time<ttl)return hit.value;
  if(mcPendingReads.has(key))return mcPendingReads.get(key);
  const promise=db.ref(path).orderByChild(child).equalTo(value).once("value").then(snap=>{const value=snap.val()||{};mcMemoryCache.set(key,{time:Date.now(),value});return value}).finally(()=>mcPendingReads.delete(key));
  mcPendingReads.set(key,promise);return promise;
}

function createAssessmentSession(uid,meta={}){if(!uid)return Promise.resolve(null);const ref=db.ref(`assessmentSessions/${uid}`).push();return ref.set({uid,mode:meta.mode||"practice",scopeKey:meta.scopeKey||"",subject:meta.subject||null,topicId:meta.topicId||null,topic:meta.topic||null,questionIds:Array.isArray(meta.questionIds)?meta.questionIds:[],status:"active",startedAt:firebase.database.ServerValue.TIMESTAMP}).then(()=>ref.key)}
async function lockAssessmentAnswer(uid,sessionId,index,answer){if(!uid||!sessionId||!answer)return false;const ref=db.ref(`assessmentSessions/${uid}/${sessionId}/answers/${index}`);const snap=await ref.once("value");if(snap.exists())return String(snap.val())===String(answer);await ref.set(String(answer));return true}
async function loadLockedAssessmentAnswers(uid,sessionId){if(!uid||!sessionId)return{};try{const s=await db.ref(`assessmentSessions/${uid}/${sessionId}/answers`).once("value");return s.val()||{}}catch(e){return{}}}
async function closeAssessmentSession(uid,sessionId,status="completed"){
  if(!uid||!sessionId)return;
  const ref=db.ref(`assessmentSessions/${uid}/${sessionId}`);
  await ref.child("status").set(status);
  await ref.child("completedAt").set(firebase.database.ServerValue.TIMESTAMP);
}
function deviceId(){const key="mathcloud_device_id";let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,id)}return id}
function whatsappActivationLink(name="",email="",number=""){
  const clean=String(number||"").replace(/\D/g,"");
  const text=`Hello MathCloud Tutorial, I have paid for JAMB preparation. My name is ${name}. My email is ${email}. Please activate my account.`;
  return clean?`https://wa.me/${clean}?text=${encodeURIComponent(text)}`:"#";
}
async function saveUserProfile(user,data={}){
  const ref=db.ref(`users/${user.uid}`),snap=await ref.once("value"),existing=snap.val()||{};
  const merged={...existing,uid:user.uid,email:user.email||existing.email||"",displayName:user.displayName||existing.displayName||"",...data,updatedAt:firebase.database.ServerValue.TIMESTAMP};
  if(!merged.subscription) merged.subscription={status:"pending",amount:MATHCLOUD_CONFIG.annualFee,durationDays:MATHCLOUD_CONFIG.subscriptionDays};
  await ref.set(merged);
}
function subscriptionActive(userData){return !!userData&&userData.subscription?.status==="active"&&Number(userData.subscription?.expiryAt||0)>Date.now()}
async function isAdmin(user=auth.currentUser){
  if(!user)return false;
  try{
    await user.reload();
    const fresh=auth.currentUser||user;
    const snap=await db.ref(`admins/${fresh.uid}`).once("value");
    const record=snap.val();
    return record?.role==="admin" && record?.uid===fresh.uid;
  }catch(e){
    console.error("Admin verification failed",e);
    return false;
  }
}
async function ensureBootstrapAdmin(user){
  if(!user)return false;
  const email=String(user.email||"").trim().toLowerCase();
  const bootstrap=String(MATHCLOUD_CONFIG.initialAdminEmail||"").trim().toLowerCase();
  if(!user.emailVerified || !bootstrap || email!==bootstrap)return false;
  const ref=db.ref(`admins/${user.uid}`);
  const snap=await ref.once("value");
  if(snap.val()?.role==="admin" && snap.val()?.uid===user.uid)return true;
  await ref.set({uid:user.uid,name:user.displayName||"Administrator",email:user.email,role:"admin",createdAt:snap.val()?.createdAt||firebase.database.ServerValue.TIMESTAMP});
  return true;
}
async function requireStudentAuth(onReady){
  auth.onAuthStateChanged(async user=>{
    if(!user){location.replace("index.html");return}
    try{
      const fresh=auth.currentUser||user;
      const uid=fresh.uid;
      const [userSnap,adminSnap]=await Promise.all([
        db.ref(`users/${uid}`).once("value"),
        db.ref(`admins/${uid}`).once("value")
      ]);
      if(adminSnap.val()?.role==="admin"&&adminSnap.val()?.uid===uid){location.replace("../admin/index.html");return}
      let data=userSnap.val()||{};
      if(!data.uid){
        await saveUserProfile(fresh,{provider:fresh.providerData?.[0]?.providerId||"unknown"});
        data=(await db.ref(`users/${uid}`).once("value")).val()||{};
      }
      const gate=await enforceSingleDevice(fresh);
      if(!gate.allowed){await auth.signOut();showNotice(gate.reason,"error");return}
      renderStudentWelcome(fresh,data,document.title);
      await onReady(fresh,data);
    }catch(e){console.error(e);showNotice("We could not load your account. Please try again.","error")}
  });
}
async function requireAdminAuth(onReady){
  auth.onAuthStateChanged(async user=>{
    if(!user){location.replace("../student/index.html");return}
    try{
      await user.reload();
      const fresh=auth.currentUser||user;
      let admin=await isAdmin(fresh);
      if(!admin && await ensureBootstrapAdmin(fresh)) admin=await isAdmin(fresh);
      if(!admin){
        const verified=fresh.emailVerified?"verified":"not verified";
        showNotice(`Administrator access could not be verified. The signed-in account is ${verified} and has no protected admin record.` ,"error");
        setTimeout(()=>location.replace("../student/index.html"),2500);
        return;
      }
      await onReady(fresh);
    }catch(e){
      console.error("Administrator verification error",e);
      showNotice("Administrator access could not be verified. Check that the deployed Firebase database rules match this package.","error");
    }
  });
}
async function enforceSingleDevice(user){
  const id=deviceId(),ref=db.ref(`deviceSessions/${user.uid}`),snap=await ref.once("value"),current=snap.val();
  if(current?.locked&&current.deviceId&&current.deviceId!==id)return{allowed:false,reason:"This account is already active on another device. Please contact MathCloud Tutorial to request a device unlock."};
  const sessionId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
  await ref.set({deviceId:id,locked:true,sessionId,lastSeenAt:firebase.database.ServerValue.TIMESTAMP});
  return{allowed:true};
}
function startSessionHeartbeat(user){
  const id=deviceId(),ref=db.ref(`deviceSessions/${user.uid}`);
  const check=async()=>{try{const s=await ref.once("value"),v=s.val();if(v?.locked&&v.deviceId&&v.deviceId!==id){await auth.signOut();location.replace("index.html")}else if(v?.deviceId===id&&v.locked){await ref.update({lastSeenAt:firebase.database.ServerValue.TIMESTAMP})}}catch(e){console.warn("Session heartbeat failed")}};
  check();return setInterval(check,30000);
}
function openConfirm(message,onYes){
  const overlay=$("#confirmModal");if(!overlay){return Promise.resolve(onYes())}
  $("#confirmMessage").textContent=message;overlay.hidden=false;const yes=$("#confirmYes"),no=$("#confirmNo");
  const close=()=>{overlay.hidden=true;yes.onclick=null;no.onclick=null};
  yes.onclick=()=>{close();Promise.resolve(onYes()).catch(e=>{console.error(e);showNotice("The action could not be completed.","error")})};no.onclick=close;
}
function getStudentSubjects(data){const subjects=Array.isArray(data?.subjects)?data.subjects.filter(Boolean):[];return subjects.length?subjects:[]}
function studentHasSubject(data,subjectId){return getStudentSubjects(data).includes(String(subjectId||""))}
function whatsappCourseRequestLink(name="",email="",number="",course="",subjects=[]){const clean=String(number||"").replace(/\D/g,"");const subjectText=(Array.isArray(subjects)?subjects:[]).join(", ");const text=`Hello MathCloud Tutorial, I am requesting a change to my JAMB course/subjects. My name is ${name}. My email is ${email}. Current course: ${course||"Not set"}. Current subjects: ${subjectText||"Not set"}. Please review my request.`;return clean?`https://wa.me/${clean}?text=${encodeURIComponent(text)}`:"#";}
// One-on-one / video lesson requests: saved to Firebase for admin visibility, and
// simultaneously fast-tracked to MathCloud Tutorial on WhatsApp with the same details.
function whatsappLessonRequestLink({type="one-on-one",name="",email="",subject="",topic="",preferredTime="",notes="",number=""}={}){
  const clean=String(number||MATHCLOUD_CONFIG?.whatsappNumber||"").replace(/\D/g,"");
  const kind=type==="video"?"a video lesson":"a one-on-one lesson";
  const lines=[
    `Hello MathCloud Tutorial, I would like to request ${kind}.`,
    "",
    `Name: ${name||"Not provided"}`,
    `Email: ${email||"Not provided"}`,
    `Subject: ${subject||"Not specified"}`,
    `Topic: ${topic||"Not specified"}`,
    `Preferred time: ${preferredTime||"Flexible / any time"}`,
    notes?`Notes: ${notes}`:null,
    "",
    "Please confirm availability. Thank you."
  ].filter(x=>x!==null);
  return clean?`https://wa.me/${clean}?text=${encodeURIComponent(lines.join("\n"))}`:"#";
}
async function submitLessonRequest(uid,payload={}){
  if(!uid)return null;
  const ref=db.ref(`lessonRequests/${uid}`).push();
  await ref.set({status:"requested",requestedAt:firebase.database.ServerValue.TIMESTAMP,...payload});
  return ref.key;
}
function openWhatsApp(link){if(!link||link==="#")return;window.open(link,"_blank","noopener,noreferrer")}
function calculatorNeededFor(subjectId){return (MATHCLOUD_CONFIG?.calculatorSubjects||[]).includes(String(subjectId||"").trim().toLowerCase())}
async function syncStudentSubjectAccess(uid,subjects){if(!uid)return;const map={};(Array.isArray(subjects)?subjects:[]).filter(Boolean).forEach(id=>{map[String(id)]=true;});await db.ref(`studentSubjectAccess/${uid}`).set(map);}
function setLogo(scope="MathCloud Tutorial",href=null){
  const host=document.querySelector("[data-brand]");if(!host)return;
  host.innerHTML=`<img src="${href||host.dataset.brandLogo||"../assets/logo.png"}" alt="MathCloud Tutorial logo"><span>${escapeHtml(scope)}</span>`;
}


function assessmentPercentage(score,total){return total?Number((100*Number(score||0)/Number(total)).toFixed(1)):0;}
function safePct(c,t){return t?Math.max(0,Math.min(100,(Number(c)||0)/Number(t)*100)):0;}
function analysisBand(p){p=Number(p)||0;return p>=85?"Very Good":p>=75?"Good":p>=65?"Average":p>=50?"Fair":"Weak";}
function analysisBandClass(p){return analysisBand(p).toLowerCase().replace(/\s+/g,"-");}
function jambSubjectMax(subjectId){return String(subjectId||"").toLowerCase()==="english"?160:80;}
function getAssessmentSubjectBreakdown(r){
  const out={};
  if(r&&r.subjectBreakdown&&typeof r.subjectBreakdown==="object"){
    Object.entries(r.subjectBreakdown).forEach(([sid,v])=>{
      const total=Number(v?.total||0),correct=Number(v?.correct??v?.score??0);
      if(total>0)out[sid]={subject:sid,subjectName:v?.subjectName||sid,correct,total};
    });
  }
  if(!Object.keys(out).length&&r?.mode==="mock"&&r?.subject){
    const sid=String(r.subject),total=Number(r.total||0),correct=Number(r.score||0);
    if(total>0)out[sid]={subject:sid,subjectName:r.subjectName||sid,correct,total};
  }
  if(!Object.keys(out).length&&r?.mode==="mock"&&r?.mockSubject){
    const sid=String(r.mockSubject),total=Number(r.total||0),correct=Number(r.score||0);
    if(total>0)out[sid]={subject:sid,subjectName:r.subjectName||sid,correct,total};
  }
  return out;
}
function calculateMockPerformance(rows,registeredSubjects=[]){
  const subjectMap={};
  (rows||[]).filter(r=>r?.mode==="mock").forEach(r=>{
    Object.values(getAssessmentSubjectBreakdown(r)).forEach(v=>{
      const sid=String(v.subject),score=Math.max(0,Math.min(jambSubjectMax(sid),Number(v.correct||0)/Number(v.total||1)*jambSubjectMax(sid)));
      if(!subjectMap[sid])subjectMap[sid]={subject:sid,subjectName:v.subjectName||sid,max:jambSubjectMax(sid),scores:[],best:0,average:0};
      subjectMap[sid].scores.push(score);subjectMap[sid].best=Math.max(subjectMap[sid].best,score);
    });
  });
  const ids=[...(Array.isArray(registeredSubjects)?registeredSubjects:[]).map(String),...Object.keys(subjectMap)];
  const unique=[...new Set(ids.filter(Boolean))];
  unique.forEach(sid=>{if(!subjectMap[sid])subjectMap[sid]={subject:sid,subjectName:sid,max:jambSubjectMax(sid),scores:[],best:0,average:0};const s=subjectMap[sid];s.average=s.scores.length?s.scores.reduce((a,b)=>a+b,0)/s.scores.length:0;});
  const list=unique.map(sid=>subjectMap[sid]);
  const best400=Math.round(list.reduce((n,s)=>n+s.best,0));
  const average400=Math.round(list.reduce((n,s)=>n+s.average,0));
  return {subjects:list,allTimeBest400:Math.max(0,Math.min(400,best400)),average400:Math.max(0,Math.min(400,average400))};
}
function overallPreparation400(rows,registeredSubjects=[]){return calculateMockPerformance(rows,registeredSubjects).allTimeBest400;}
function getSubjectTopicCatalog(subjectNode){
  const entries=[];
  const raw=subjectNode?.topics||{};
  if(Array.isArray(raw)){
    raw.forEach((x,i)=>{const id=String(x?.id||x?.topicId||topicKey(x?.name||x?.topic||x?.title)||i),name=String(x?.name||x?.topic||x?.title||id);entries.push({id,name});});
  }else if(raw&&typeof raw==="object"){
    Object.entries(raw).forEach(([id,x])=>{const name=typeof x==="string"?x:String(x?.name||x?.topic||x?.title||id);entries.push({id:String(id),name});});
  }
  const seen=new Set();return entries.filter(x=>{const k=topicKey(x.id)+"::"+topicKey(x.name);if(seen.has(k))return false;seen.add(k);return true;});
}
function buildMockTopicAnalysis(rows,subjectCatalog={}){
  const attempted={};
  (rows||[]).filter(r=>r?.mode==="mock").forEach(r=>{
    Object.entries(getAssessmentSubjectBreakdown(r)).forEach(([sid,v])=>{
      Object.values(v.topics||{}).forEach(t=>{
        const topic=String(t?.topic||t?.topicName||t?.name||"General"),key=String(sid)+"::"+topicKey(topic),total=Number(t?.total||0),correct=Number(t?.correct||0);
        if(!total)return;
        if(!attempted[key])attempted[key]={subject:sid,subjectName:v.subjectName||sid,topic,attempts:0,total:0,correct:0};
        attempted[key].attempts++;attempted[key].total+=total;attempted[key].correct+=correct;
      });
    });
    if(r.topicBreakdown&&typeof r.topicBreakdown==="object")Object.values(r.topicBreakdown).forEach(t=>{
      const sid=String(t?.subject||r.subject||r.mockSubject||"unknown"),topic=String(t?.topic||"General"),key=sid+"::"+topicKey(topic),total=Number(t?.total||0),correct=Number(t?.correct||0);
      if(!total)return;if(!attempted[key])attempted[key]={subject:sid,subjectName:t?.subjectName||sid,topic,attempts:0,total:0,correct:0};attempted[key].attempts++;attempted[key].total+=total;attempted[key].correct+=correct;
    });
  });
  const bySubject={};
  Object.entries(subjectCatalog||{}).forEach(([sid,node])=>{
    const available=getSubjectTopicCatalog(node);const availKeys=new Set(available.map(t=>topicKey(t.id)+"::"+topicKey(t.name)));
    const attemptedForSubject=Object.values(attempted).filter(t=>t.subject===sid);
    bySubject[sid]={subject:sid,subjectName:node?.name||sid,availableCount:available.length,exposedCount:attemptedForSubject.length,
      strong:attemptedForSubject.filter(t=>safePct(t.correct,t.total)>=75).sort((a,b)=>safePct(b.correct,b.total)-safePct(a.correct,a.total)),
      weak:attemptedForSubject.filter(t=>safePct(t.correct,t.total)<65).sort((a,b)=>safePct(a.correct,a.total)-safePct(b.correct,b.total)),
      developing:attemptedForSubject.filter(t=>safePct(t.correct,t.total)>=65&&safePct(t.correct,t.total)<75),
      notExposed:available.filter(t=>{
        const tk=topicKey(t.id)+"::"+topicKey(t.name);
        return !Object.keys(attempted).some(k=>k===sid+"::"+topicKey(t.name)||k===sid+"::"+topicKey(t.id));
      }).map(t=>t.name)
    };
    bySubject[sid].notExposedCount=bySubject[sid].notExposed.length;
  });
  Object.values(attempted).forEach(t=>{if(!bySubject[t.subject])bySubject[t.subject]={subject:t.subject,subjectName:t.subjectName||t.subject,availableCount:0,exposedCount:0,strong:[],weak:[],developing:[],notExposed:[],notExposedCount:0};});
  return {bySubject,attempted:Object.values(attempted)};
}
function installPageProtection(){
  if(window.__mcPageProtection)return;window.__mcPageProtection=true;
  document.addEventListener("contextmenu",e=>{e.preventDefault();showNotice("Right-click is disabled on this page.","warning");});
  document.addEventListener("keydown",e=>{
    const k=String(e.key||"").toLowerCase(),blocked=e.key==="F12"||(e.ctrlKey&&e.shiftKey&&["i","j","c"].includes(k))||(e.ctrlKey&&k==="u");
    if(blocked){e.preventDefault();e.stopPropagation();showNotice("Developer tools / page-source shortcuts are disabled on this page.","warning");return false;}
  },true);
}
installPageProtection();

function getNextLearningRecommendation(rows=[],subjectCatalog={},registeredSubjects=[]){
  const totals={};
  (rows||[]).filter(r=>r?.mode==="topic"||r?.mode==="mock").forEach(r=>{
    if(r.topicBreakdown&&typeof r.topicBreakdown==="object") Object.values(r.topicBreakdown).forEach(t=>{
      const sid=String(t?.subject||r.subject||r.mockSubject||"");
      const topic=String(t?.topic||t?.topicName||r.topic||"General");
      const total=Number(t?.total||0),correct=Number(t?.correct||0);
      if(!sid||!total)return;
      const key=sid+"::"+topicKey(topic);
      if(!totals[key])totals[key]={subject:sid,subjectName:t?.subjectName||subjectCatalog?.[sid]?.name||sid,topic,correct:0,total:0,attempts:0};
      totals[key].correct+=correct;totals[key].total+=total;totals[key].attempts++;
    });
    if(r.mode==="topic"&&!r.topicBreakdown){
      const sid=String(r.subject||"");const topic=String(r.topic||"General"),total=Number(r.total||0),correct=Number(r.score||0);
      if(sid&&total){const key=sid+"::"+topicKey(topic);if(!totals[key])totals[key]={subject:sid,subjectName:r.subjectName||subjectCatalog?.[sid]?.name||sid,topic,correct:0,total:0,attempts:0};totals[key].correct+=correct;totals[key].total+=total;totals[key].attempts++;}
    }
  });
  const attempted=Object.values(totals).map(x=>({...x,pct:safePct(x.correct,x.total)}));
  attempted.sort((a,b)=>a.pct-b.pct||b.total-a.total);
  const weak=attempted.find(x=>x.pct<65);
  if(weak)return {type:"focus",...weak,message:`Focus next on ${weak.topic} in ${weak.subjectName}. Your recorded accuracy is ${weak.pct.toFixed(1)}%.`};
  const developing=attempted.find(x=>x.pct<75);
  if(developing)return {type:"developing",...developing,message:`Keep building ${developing.topic} in ${developing.subjectName}. Your recorded accuracy is ${developing.pct.toFixed(1)}%.`};
  const available=[];
  (registeredSubjects||[]).forEach(sid=>{const node=subjectCatalog?.[sid];getSubjectTopicCatalog(node).forEach(t=>{const key=String(sid)+"::"+topicKey(t.name);if(!totals[key])available.push({subject:sid,subjectName:node?.name||sid,topic:t.name,pct:null,total:0})})});
  if(available.length)return {type:"new",...available[0],message:`Start a new topic: ${available[0].topic} in ${available[0].subjectName}.`};
  return {type:"maintain",message:"Keep rotating your registered topics and complete timed mocks regularly."};
}

function readinessBand(pct){const p=Number(pct)||0;if(p>=80)return{label:"Excellent readiness",level:"excellent",advice:"You are performing strongly. Maintain timed practice and close small topic gaps."};if(p>=70)return{label:"Good readiness",level:"good",advice:"You are on a good path. Focus on weaker topics and keep doing full mocks."};if(p>=60)return{label:"Developing readiness",level:"developing",advice:"You are improving. Increase targeted practice before relying on full mocks."};return{label:"Needs focused preparation",level:"focus",advice:"Build your foundation with topic practice, corrections and repeated timed work."};}
function installNoPrint(){window.addEventListener("beforeprint",()=>{showNotice("Printing is disabled for student result pages. Request a printable report from the administrator.","warning")});window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="p"){e.preventDefault();showNotice("Printing is disabled for student result pages. Request a printable report from the administrator.","warning")}});}


// Live question-bank utilities. All student assessments read the Firebase question bank;
// these helpers only normalise records and select a fresh random sample in memory.
function normalizeAssessmentQuestion(raw, id=""){
  if(!raw || typeof raw!=="object" || Array.isArray(raw)) return null;
  const options = raw.options && typeof raw.options === "object" && !Array.isArray(raw.options)
    ? raw.options
    : {
        A: raw.optionA ?? raw.A ?? raw.option_a,
        B: raw.optionB ?? raw.B ?? raw.option_b,
        C: raw.optionC ?? raw.C ?? raw.option_c,
        D: raw.optionD ?? raw.D ?? raw.option_d,
        E: raw.optionE ?? raw.E ?? raw.option_e
      };
  const question = raw.question ?? raw.questionText ?? raw.text ?? raw.question_text ?? "";
  const answer = raw.correctAnswer ?? raw.correct ?? raw.answer ?? raw.correctOption ?? raw.correct_option ?? "";
  const cleanOptions={};
  Object.entries(options).forEach(([k,v])=>{
    if(v!==undefined && v!==null && String(v).trim()!=="") cleanOptions[String(k).toUpperCase()]=v;
  });
  if(!String(question).trim() || !String(answer).trim() || Object.keys(cleanOptions).length<2) return null;
  let correctAnswer=String(answer).trim();
  const answerKey=correctAnswer.toUpperCase();
  if(cleanOptions[answerKey]!==undefined) correctAnswer=answerKey;
  else {
    const byText=Object.entries(cleanOptions).find(([,v])=>String(v).trim()===correctAnswer);
    if(byText) correctAnswer=byText[0];
  }
  return {...raw,id:String(raw.id||id),question:String(question),options:cleanOptions,correctAnswer};
}
function flattenAssessmentQuestions(value,prefix=""){
  const out=[];
  if(!value || typeof value!=="object") return out;
  Object.entries(value).forEach(([id,node])=>{
    if(node && typeof node==="object" && !Array.isArray(node)){
      const q=normalizeAssessmentQuestion(node,id);
      if(q) out.push(q);
      else out.push(...flattenAssessmentQuestions(node,prefix?`${prefix}/${id}`:id));
    }
  });
  return out;
}
function assessmentQuestionMatches(q,{subjectId,topicId,topicName}={}){
  if(!q) return false;
  const wantedSubject=String(subjectId||"").trim().toLowerCase();
  const qSubjects=[q.subject,q.subjectId,q.subjectKey,q.subject_id].filter(Boolean).map(x=>String(x).trim().toLowerCase());
  if(wantedSubject && !qSubjects.includes(wantedSubject)) return false;
  if(topicId==null && topicName==null) return true;
  const wantedIds=[topicId,topicName].filter(x=>x!=null && String(x).trim()!=="").map(topicKey);
  const qTopicValues=[q.topicId,q.topicIdKey,q.topic_id,q.topic,q.topicName,q.topic_name].filter(Boolean).map(topicKey);
  return wantedIds.some(w=>qTopicValues.includes(w));
}
function fisherYates(items){
  const a=[...items];
  for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}
  return a;
}
function questionFingerprint(q){
  return String(q?.question||"").replace(/<[^>]*>/g," ").replace(/\\[a-zA-Z]+|[{}$]/g," ").replace(/\s+/g," ").trim().toLowerCase();
}
async function getRecentAssessmentQuestionIds(uid,mode,scopeKey){
  if(!uid)return new Set();
  try{
    const [historySnap,attemptSnap]=await Promise.all([
      db.ref(`questionHistory/${uid}`).once("value"),
      db.ref(`studentAttempts/${uid}`).orderByChild("mode").equalTo(mode).once("value")
    ]);
    const ids=new Set(Object.keys(historySnap.val()||{}).map(String));
    const attempts=Object.values(attemptSnap.val()||{}).sort((a,b)=>Number(b.completedAt||0)-Number(a.completedAt||0));
    for(const attempt of attempts){
      if(scopeKey && attempt.scopeKey && attempt.scopeKey!==scopeKey)continue;
      for(const id of (Array.isArray(attempt.questionIds)?attempt.questionIds:[]))if(id)ids.add(String(id));
    }
    return ids;
  }catch(e){console.warn("Permanent question history could not be read; using attempt history only.",e);return new Set()}
}
async function rememberAssessmentQuestions(uid,questionIds){
  if(!uid||!Array.isArray(questionIds)||!questionIds.length)return;
  const updates={};
  [...new Set(questionIds.map(x=>String(x||"").trim()).filter(Boolean))].forEach(id=>updates[`questionHistory/${uid}/${id}`]=true);
  if(Object.keys(updates).length)await db.ref().update(updates);
}
async function selectFreshAssessmentQuestions(pool,count,{uid=null,mode="practice",scopeKey=""}={}){
  const unique=[],seenIds=new Set(),seenText=new Set();
  for(const q of (pool||[])){
    const id=String(q?.id||""),fp=questionFingerprint(q);
    if(!id||seenIds.has(id)||seenText.has(fp))continue;
    seenIds.add(id);if(fp)seenText.add(fp);unique.push(q);
  }
  const recent=await getRecentAssessmentQuestionIds(uid,mode,scopeKey);
  let available=unique.filter(q=>!recent.has(String(q.id)));
  // Recycle only after the student has genuinely exhausted this bank.
  if(available.length<count)available=unique;
  return fisherYates(available).slice(0,Math.min(count,available.length));
}
function topicKey(value){return String(value||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}


// Network resilience: give students an explicit offline screen instead of leaving a
// Firebase-dependent page spinning indefinitely. The service worker caches the whole
// app shell (all student pages + assets) so the shell itself always opens offline,
// even on a fresh device that only ever loaded the app once while online.
function installMathCloudOfflineExperience(){
  if("serviceWorker" in navigator){
    navigator.serviceWorker.register("../sw.js",{scope:"../"}).then(reg=>{
      // Pick up a newer service worker automatically instead of leaving students stuck
      // on a stale cached shell after an update is published.
      reg.addEventListener("updatefound",()=>{
        const fresh=reg.installing;if(!fresh)return;
        fresh.addEventListener("statechange",()=>{
          if(fresh.state==="installed"&&navigator.serviceWorker.controller)fresh.postMessage({type:"SKIP_WAITING"});
        });
      });
      setInterval(()=>reg.update().catch(()=>{}),10*60*1000);
    }).catch(()=>{});
    let reloaded=false;
    navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloaded)return;reloaded=true;location.reload()});
  }
  let wasOffline=!navigator.onLine;
  const update=()=>{
    let banner=document.getElementById("mcNetworkBanner");
    if(!navigator.onLine){
      wasOffline=true;
      if(banner)return;
      banner=document.createElement("div");banner.id="mcNetworkBanner";banner.className="mc-offline";
      banner.innerHTML=`<div class="mc-offline-card"><img src="../assets/logo.png" alt="MathCloud Tutorial"><div class="mc-online-dot" style="justify-content:center;color:#b42318">You are offline</div><h1>No internet connection</h1><p>MathCloud needs an internet connection to load live JAMB questions, save answers and submit results. This page's shell is cached, so it stays visible while you reconnect.</p><button class="btn btn-primary" onclick="location.reload()">Try again</button></div>`;
      document.body.appendChild(banner);
    }else{
      if(banner)banner.remove();
      if(wasOffline){wasOffline=false;showNotice("You are back online.","success")}
    }
  };
  window.addEventListener("online",update);window.addEventListener("offline",update);update();
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",installMathCloudOfflineExperience);else installMathCloudOfflineExperience();
